# Generated by Django 4.2.1 on 2024-05-27 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maest_app', '0004_alter_producto_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertastockbajo',
            name='leido',
            field=models.BooleanField(default=False),
        ),
    ]
