# Generated by Django 4.2.1 on 2024-06-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maest_app', '0005_alertastockbajo_leido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('terminos_pago', models.CharField(blank=True, max_length=200, null=True)),
                ('inhabilitado', models.BooleanField(default=False)),
            ],
        ),
    ]
