# Generated by Django 4.2.1 on 2024-06-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maest_app', '0006_proveedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='terminos_pago',
            new_name='modalidad_pago',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='contacto',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='giro',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
