# Generated by Django 4.2.1 on 2024-06-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maest_app', '0007_rename_terminos_pago_proveedor_modalidad_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='modalidad_pago',
            field=models.CharField(choices=[('Cheque', 'Cheque'), ('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia')], default='Efectivo', max_length=20),
        ),
    ]
