# Generated by Django 5.0.4 on 2024-06-15 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maest_app', '0009_historialprecios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialprecios',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
