# Generated by Django 4.2.1 on 2024-09-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maest_app', '0011_alter_producto_ubicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.FileField(upload_to='informes/')),
            ],
        ),
    ]
